### ISSUE TITLE
跑馬燈的箭頭，在css及js的名稱有錯誤

### ISSUE THREAD

**Issue by anniewuu00** [HywebU00/HyUI_v4#17]
跑馬燈的箭頭，在css及js的名稱有錯誤

應為 marquee-prev及 marquee-next
css
 &.marquee-prev {
        top: 0;
      }
      &.marquee-next {
        bottom: 0;
        left: 4px;
        &::before {
          transform: rotate(180deg);
        }
      }

js
 // 切換箭頭
    navigation: {
      nextEl: '.marquee .**marquee-prev'**, //自行設定樣式
      prevEl: '.marquee .**marquee-next'**, //自行設定樣式
    },

**Comment by tseng7510** [comment]
這個是文件錯誤，已更新
https://github.com/HywebU00/HyUI4.0_document/commit/5c454d06f4d8fe04e17ae4ee7f792c96581383ba
